---
- hosts: general_servers
  tasks:
    - name: get values
      ansible.builtin.shell: 
        cmd: (find . -maxdepth 1 -type d -print0 | xargs -0 stat ) || printf "%s Not found %n"
        chdir: /var/www/
        executable: /bin/bash 
      register: grep_output
      ignore_errors: true
    
    - name: Print   
      debug:
        msg: "{{ inventory_hostname }}: '{{ grep_output.stdout }}'"

      



