---
- hosts: general_servers
  tasks:
  - name: Restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
    ansible.builtin.systemd_service:
      state: restarted
      daemon_reload: true
      name: zabbix-agent
