
- name: Creación fichero actualizaciones
  hosts: general_servers
  user: ansible
  become: true
  gather_facts: true
  vars:
  tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
